//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public int Id { get; set; }
        public byte[] InitialData { get; set; }
        public byte[] Data { get; set; }
    }
}
